# Generated by Django 4.0.4 on 2022-08-09 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
